// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { FlyoutPageProvider } from "./components/(Flyouts)/(Provider)/FlyoutPageContextProvider";
import HeaderCMP from "./components/HeaderCMP";
import { getUserFromSession } from "./(Auth)/lib/session";


const myFont = localFont({
  src: './fonts/Vazirmatn-RD-FD-Regular.woff2',
})
export const metadata: Metadata = {
	title: "ManaMode",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// ✅ دریافت اطلاعات کاربر از session
  const initialUser = await getUserFromSession();
	return (
		<html lang="en" className="w-full bg-white">
			<body dir="rtl" className={`${myFont.className} w-full antialiased relative `} >
				
					<FlyoutPageProvider initialUser={initialUser}>
						
						<HeaderCMP className="flex sticky header_height  top-0 z-2 items-center  bg-sky-500/30  backdrop-blur-sm border-b border-b-gray-400/30 
						landscape:w-full  landscape:lg:px-20 landscape:px-5  shrink-0
						portrait:w-full    portrait:px-4  " />
					
						<div id="content"  className="landscape:w-[85%] portrait:w-full  mx-auto z-1 ">
							{children} 
						</div>
						<footer className="w-full  shrink-0 pb-4 z-1">
							<div className="w-full h-[300px] shrink-0 bg-gray-900"></div>
						</footer>
						<div className="fixed top-0 w-full h-[50%]   bg-linear-180 from-sky-600  to-white -z-1"></div>
					</FlyoutPageProvider>
				
				
			</body>
		</html>
	);}
